### ISSUE TITLE
fatal error gta 5 scriphookv

### ISSUE THREAD

**Issue by FindMuck** [Guad/MapEditor#1]
fatal error: directx texture
creation failed C:\Users\Name\AppData\Local\Temp\tmpF228.tmp

**Comment by Guad** [comment]
Did you run it as admin? Anyways, you can work around this by using Orb crosshair instead.

**Comment by FindMuck** [comment]
I have steam version and this can not run as admin. Why I should take orb no crosshair?

**Comment by Guad** [comment]
Yes it can, use google.
