### ISSUE TITLE
Change loading/offloading of maps with different programming language.

### ISSUE THREAD

**Issue by hennysmafter** [Guad/MapEditor#2]
Dear Guadmaz.

Let me first start with thanking you for letting us use this mod. As it is amazing and we have been enjoying ourselves building some nice interiors for The Savehouse Mod. We are planning on building 69 house interiors and 20+ hotel/apartments (this is going to take a while :-) ) but we just done 2 trailers and 1 house.

And we are experiencing FPS drop as well as the users of our mod especially by the house. These interiors are built inside ingame exteriors. 

What we would love to do is to load a map when going inside and unload going outside. We written our mod in the .lua language. But we are looking into converting to C++ and maybe C#.

Can you advise us on how we could do that. And if it is possible to do it with .lua and/or C++.

**Comment by Guad** [comment]
If you're using c#, you can set map editor output to C# code and then just copy paste into your script
