### ISSUE TITLE
???

### ISSUE THREAD

**Issue by MrMpunit** [Guad/MapEditor#3]
Can't help but ask, on a former issue you posted.....

GTACoop
"This mod is no longer supported. I'm working on another multiplayer mod, which is not focused on co-op."

I'm just wondering if you've found the time to develop such a mod?

**Comment by Guad** [comment]
I'm still working on it

**Comment by MrMpunit** [comment]
Is there an ETA or a way someone can get into like an alpha?

**Comment by Guad** [comment]
Not yet
